@startuml

title Контекстная диаграмма (To-Be)

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

' Актеры
Person(user, "Пользователь", "Управляет домом через Веб-интерфейс/мобильный клиент.")
Person(administrator, "Администратор", "Поддержка и администрирование платформы.")

' Внутренние системы
System_Boundary(systemHouse, "Облако «Тёплый дом»") {
  System(houseServer, "Платформа умного дома (SaaS)", "Управление устройствами, сценарии, телеметрия, уведомления, подписки")
}

System_Boundary(systemHub, "Дом пользователя") {
    System(hub, "Хаб", "Центральное устройство для подключения и управления устройствами по стандартным протоколам")
    System(device, "Устройства и датчики", "Устройство, подключенные к системе")
}

' Связи
Rel(user, houseServer, "Добавляет, управляет и получает информацию с устройств. Создает сценарии")
Rel(administrator, houseServer, "Администрирование и поддержка пользователей, устройства, сценарии, тарифы")
Rel(houseServer, hub, "Управляет и получает данные с устройств")
Rel(device, hub, "Отправляет данные")
Rel(hub, device, "Управляет устройством")

@enduml